before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: w0+ot9VgcAzFe62X8seAwdfhFLQN7MEYKZccQD99uSmQuT1IiNF+n2zHbueqcp4wV0ySrvx3R2LpXseDW3lj4uboiyplNW7LxdmTrqLn8Ucm1EngdVa05AG0Nwmt9akIrXmDBepCyhDrtssnSLAWBuI+HhsrEIAKPEnLo29reoD/3qAmx8zL3JO54VEkxPeNgbOTJzQsvBBP0fEoaMcQlstMEBaYO1KJKZtSBkFxw2HN6B8mqdp8LB+PrEUdHLiYF+/oaZSL/ZO+dpS/LB3Qpbddrl+ifgmVBte8W3+UtMjaVz2oGetX55dWiMKqKtJphcOZgUM3OxGCv4hkzkKmO+zPn4J9ZKmYzyvLrbv3lPtm1slERagHVEt72GOheZvRif+cVBZ9F7vzOfM4ZorGnixh2AtOxccIt/9jhF7a5n23g4QaMaxrSman6lPsXj6cZq+bZu6jlpIafBzNy1lEMh8Bgasafbnxo0bRBS78EcIrOD/1l+jeHohBme1z1NAbtZXeZjagEhdwBcebJkWRTm1MvX/xjCTvHkWDJkM4bQjdLkIOoxEquXJtZsH/KOkKTwZmDXsqmLoqQtTaKtEyvfOGkxiSNsCLq0qqqHZC2dJ0i2ci/XimcXTccNCHmalIQVw+kk9TRVzRZtSwjjTGMJLLYybNSwtVLQiRwjrtfa4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
